[package]
name = "gpio_lighttree"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11"
futures-util = { version = "0.3.31", features = ["futures-sink", "sink"] }
log = "0.4"
rppal = {version="0.22.1", features=["hal"]}
tokio = { version = "1.44.2", features = ["full"] }
tokio-util = "0.7.14"
tokio-websockets = { version = "0.11.3", features = ["server", "sha1_smol"] }
